[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pybtc"
version = "1.1.1"
authors = [
  { name="Mohanson", email="mohanson@outlook.com" },
]
description = "Python SDK for BTC"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = ["requests"]

[project.urls]
homepage = "https://github.com/mohanson/pybtc"

[tool.hatch.build.targets.wheel]
packages = ["btc"]
