[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pybtc"
version = "1.1.0"
authors = [
  { name="Mohanson", email="mohanson@outlook.com" },
]
description = "Python SDK for BTC"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = ["requests"]

[project.urls]
homepage = "https://github.com/mohanson/pybtc"
